### ISSUE TITLE
reaching out to duckduckgo hacks

### ISSUE THREAD

**Issue by goyalyashpal** [duckduckgo/duckduckhack-docs#136]
hey, so, 
i searched for [\u256D](https://duckduckgo.com/?q=%5Cu256D) and was shown this:
it felt amazing, super nice.
thanks @mintsoft and @cosimo for making this

![image](https://user-images.githubusercontent.com/19423063/178272710-f12bc46a-88ba-45a5-bbc7-c5adae6e63a9.png)

**Comment by goyalyashpal** [comment]
however, i'd like to know, how do these things function. 

like it shows stock prices, dictionary, wikipedia article, translation, map, or now this.

how does it detect what to show when?

**Comment by moollaza** [comment]
@yashpalgoyal1304 the docs in this repo describe a bit about the triggering logic. For the most part, every instant answer has trigger words or regular expressions it uses to know when to show a result.

Many of the answers themselves are open-source and available in the duckduckgo/zeroclickinfo-spice and duckduckgo/zeroclickinfo-goodies repos.

FWIW, DuckDuckHack has been in maintenance mode for quite some time now, and we're not currently accepting contributions.
