### ISSUE TITLE
Use POD documentation for Roles

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#18]
`backend-reference/goodie-helpers` contains some documentation for the GoodieRoles.

Would it be possible to move this documentation over to POD, directly in the roles (as with [WhatIs](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2644)) then have some HTML generated for this (or other means) that the docs then use?

Would make it easier to keep the documentation in sync, as well as make it a lot easier for developers to view the documentation for the roles locally.

**Comment by moollaza** [comment]
@GuiltyDolphin we previously discussed doing everything in POD or having a way to include it. For the most part, there's considerably less POD than anything else so we never integrated it.

We've recently switched to using GitBook for our docs, which doesn't seem to support POD.

We could have the docs link to the files though for the purpose of keeping it up to date.
 If we can render the POD to Markdown, we could paste that output into the docs to manually keep them in sync?

**Comment by moollaza** [comment]
@talsraviv any thoughts on this?

**Comment by talsraviv** [comment]
That sounds smart. I don't mind manually updating the docs - that sounds like the normal workflow anyways for everything else, and having POD in the files themselves doesn't hurt, as long as the duplication is one-way. 

I thought about linking. I'd prefer to keep all documentation in one place if we can, to make it more accessible to everyone, easy to navigate, and be able to add context when necessary. 

Anytime there's new functionality added feel free to make a PR on the docs repo and paste in the new function/description.... or open an issue and I'd be happy to do it.

**Comment by GuiltyDolphin** [comment]
@talsraviv Hmm... I'm trying to figure this out over on [read the docs](https://duckduckhack.readthedocs.org/en/latest/) where I can play around with the source a bit more.

I'll let you know if I come up with anything.

**Comment by GuiltyDolphin** [comment]
@talsraviv Sphinx/ReST is looking really promising for reducing code-redundancy, it lets you specify text that is repeated throughout several documents and has various other features (such as improved referencing and directives).

It even has a link checker built-in!

I'll play around with it on [one of my branches](https://github.com/GuiltyDolphin/duckduckhack-docs/tree/read-the-docs) for a while and keep you posted - the [read the docs](https://duckduckhack.readthedocs.org/en/latest/) pages will point to that.
