### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#19]
@talsraviv We've got quite a few dead links!

I've run [a quick script](https://gist.github.com/GuiltyDolphin/8cd14a370ac50a88fdd9) I wrote on the `.md` files and it has turned up quite a few bad links. Some of them may be incorrect (a few sites that I've checked out), but many of them are pointing to Goodies or Spices.

I'll try and correct as many as I can, but there are some sections in the docs that talk about instant answers that no longer exist (I'll post with a _full_ list ASAP).

**Comment by talsraviv** [comment]
Interesting! Thank you! Keeping the links alive is one of the hardest things.
