### ISSUE TITLE
Codio link goes to trial period

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckhack-docs#25]
In section 2b [on this page](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) the link to be added to the DDG organization on Codio doesn't go to a fully free page - it seems to go a trial page. Is there a new link we should use here?

(Reported [via Twitter](https://twitter.com/kayo_hamid/status/694763747324334080))

**Comment by talsraviv** [comment]
cc @moollaza

**Comment by talsraviv** [comment]
For me it works... I just created a brand new account and clicked the link:

![screen shot 2016-02-03 at 7 09 52 pm](https://cloud.githubusercontent.com/assets/1065307/12790196/c9d6e42e-caa9-11e5-847e-435cbfdf67a2.png)

**Comment by khflab** [comment]
not for me, codio redirects me to "Join a Class" page and asks me for a token.

I reported this issue. Maybe i'm doing something wrong?
![codio](https://cloud.githubusercontent.com/assets/2036324/12790391/30a8d142-ca89-11e5-8b20-d0f3b3b36256.png)

**Comment by khflab** [comment]
even if I copy and paste the token from link
![codio2](https://cloud.githubusercontent.com/assets/2036324/12790501/ad9de908-ca89-11e5-8adb-db0f2ba59b20.png)

**Comment by talsraviv** [comment]
Interesting. I think the Codio term for DuckDuckGo is 'organization' not class - I wonder if that matters. 

@moollaza knows a lot more about the codio partnership, hoping he can comment here

**Comment by tagawa** [comment]
I've now had a regular contributor say their Codio subscription has changed to a 2-week trial period. Something strange going on.

**Comment by talsraviv** [comment]
@moollaza @zekiel - sounds like it's worth reaching out to Codio. Who has been most actively in touch with them?

**Comment by talsraviv** [comment]
Hey guys - anyone still hearing of issues like this? @moollaza @tagawa any mention on the channels?

**Comment by tagawa** [comment]
No actually, and it's been fine for me.
