### ISSUE TITLE
Make it clear what aliases are for (cheat sheets)

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#26]
I've been seeing a lot of cheat sheets with things such as `X cheat sheet`, `X key bindings` etc... in the `aliases` section - we need to make it clear that aliases are **_strictly**_ for alternative names - not triggers!

What do you think, @talsraviv?

**Comment by talsraviv** [comment]
Whoa. Sorry that I just saw this now! Must have slipped my inbox. 

I agree - if that's what you're seeing I will definitely clarify.
