### ISSUE TITLE
Cheat Sheet Template Type

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/duckduckhack-docs#27]
There seems to be more than four cheat sheet template types e.g. `link` but [Documentation](http://docs.duckduckhack.com/walkthroughs/programming-syntax.html) lists only four.

Is this intentional?

**Comment by moollaza** [comment]
The Cheat Sheet reference explains the different template types -- the 2 newest types are just extensions of the Reference template so they look the same, but allow different parameters.

It looks like the `links` template hasn't been documented though
