### ISSUE TITLE
Document `links` template type for Cheat Sheets

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckhack-docs#29]
@talsraviv we have another template type, `links` that look like the reference template but allows for a `link` property (instead of `val`) that's expected to be a URL. 

This is used to create a cheat sheet made of clickable links. We currently use it for the NodeJS Tutorials Cheat Sheet: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/nodejs-tutorials.json

**Comment by talsraviv** [comment]
On it
