### ISSUE TITLE
Document Cheat Sheet support for `\n` and `\t`

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckhack-docs#33]
Cheat Sheets now support newlines and tabs (useful for code blocks).
- Any literal `\n` in the JSON will be converted to a `<br>` in the generated HTML
- Any literal `\t` in the JSON will be converted to `&nbsp;&nbsp;` in the generated HTML

If you want to show a literal `\n` or `\t` in your JSON, you need to escape the slash: `\\n` or `\\t`

E.g. https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/common-escape-sequences.json#L48

**Comment by talsraviv** [comment]
@moollaza just to be clear when you mean a literal "\n", do you mean displaying "\n" or displaying "↵"? 

Is it basically the same as how JSON.parse() would work (can I use that as a guide) or different than this:

![screen shot 2016-03-02 at 11 05 46 am](https://cloud.githubusercontent.com/assets/1065307/13466159/bc3f3f8c-e066-11e5-8a8d-a1956b3e883f.png)

and

![screen shot 2016-03-02 at 11 06 23 am](https://cloud.githubusercontent.com/assets/1065307/13466180/d27f40c6-e066-11e5-9c79-6f7f52ec862e.png)

**Comment by talsraviv** [comment]
Also - for literals in general - is this line correct?

> To express a backslash, use a quadruple backslash: `\\\\`

**Comment by moollaza** [comment]
> just to be clear when you mean a literal "\n", do you mean displaying "\n" or displaying "↵"?

I mean displaying the text: `\n` on the page like we do here: https://duckduckgo.com/?q=common+escape+sequences+cheat+sheet&ia=cheatsheet&iax=1

So, it's kinda different from `JSON.parse()` -- we're not using that FWIW.

---

> Also - for literals in general - is this line correct?
> 
> > To express a backslash, use a quadruple backslash: `\\\\`

Uh right now you need to use `\\\\` to get a `\` showing on the SERP, but that's actually kind of a bug. You should really only need `\\`. We can adjust the CheatSheet parser to better handle `\\`.

`\\\\` when parsed as JSON becomes `\\` which to our parser is an escaped `\`.

**Comment by talsraviv** [comment]
Btw - was playing in codio - is this the right usage of `\n`? I didn't get a line break, and just ran `duckpan upgrade` before it

![screen shot 2016-03-04 at 9 45 28 am](https://cloud.githubusercontent.com/assets/1065307/13530149/f182b218-e1ed-11e5-8cef-14f7c069c9cb.png)

![screen shot 2016-03-04 at 9 45 40 am](https://cloud.githubusercontent.com/assets/1065307/13530153/f5a57664-e1ed-11e5-9c84-295c11911866.png)

(didn't work for code template or keyboard template either)
