### ISSUE TITLE
Error in image for Section 0.2

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/duckduckhack-docs#42]
![image](https://cloud.githubusercontent.com/assets/5793364/13567535/c23d188a-e496-11e5-9a1d-faf5c830ed0d.png)

Noticed that the filepath for the HackerNews Perl file shows `lib/DDG/Goodie/HackerNews.pm` instead of `lib/DDG/Spice/HackerNews.pm`.

**Comment by talsraviv** [comment]
Ooo - thanks! On it.
