### ISSUE TITLE
Remove reference to 'simple' structured answers

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#44]
There's some doc sections that make reference to the 'simple' structured answers:

![screenshot from 2016-03-12 19 22 12](https://cloud.githubusercontent.com/assets/8598426/13724783/d0aecc70-e887-11e5-936a-f691f52f4c8c.png)

Do we even support these still? AFAICT we are updating all previously 'simple' structured answers to use the new templates - which are more versatile and _much_ more maintainable.

I would vote on removing reference to 'simple' structured answers - and focus on getting people using the full templates so that they _know_ what's available, and have experience working with them which they can use when making more complex Instant Answers.

Maybe there is still a place for them - but I find it isn't much effort to _just use a full template_ rather than the simplified version - and they are also a nightmare with tests!

What do you guys think? Encourage the use? Discourage the use? Wipe them completely?

/cc @talsraviv @moollaza @duckduckgo/community-leaders

**Comment by moollaza** [comment]
> Do we even support these still? AFAICT we are updating all previously 'simple' structured answers to use the new templates - which are more versatile and much more maintainable.

Yes these are still technically supported, they use different, older Handlebars templates though which I'd like to avoid.

> I would vote on removing reference to 'simple' structured answers - and focus on getting people using the full templates so that they know what's available, and have experience working with them which they can use when making more complex Instant Answers.

I think ultimately this is where we want to end up -- a unified way of creating a templated IA. The "simple structured_answer" was a half-way step before we had full template support.

> What do you guys think? Encourage the use? Discourage the use? Wipe them completely?

I'd like to see us migrate everything to full templates and then we can remove the `simple structured_answer` which should simplify the docs a bit. 

---

@zachthompson what are your thoughts on all this?

I still like the idea of a simplified approach to a full templated answer, but I don't like how different the two current approaches are, specifically the language of `title` and `subtitle` (used elsewhere) vs `result`, `input`, `operation` (only in Goodies).

Perhaps if you only specify `title` and `subtitle` we can infer this is a Goodie using the text template?

**Comment by GuiltyDolphin** [comment]
@moollaza Simplifying the docs would definitely be a big bonus! Having exceptions ("if your instant answer only...") around the place might make it harder to understand!

I'm not entirely sure what you mean by your last point? I agree there isn't much difference between the 'simple' structured answers and templates (both use a structured answer) - which may lead to confusion down the line when introduced to 'full' templates, but why do we need to determine whether or not they are Goodies? Isn't that the job of the metadata on duck.co?

I appreciate that last bit may have been aimed at @zachthompson, but I'm curious! :wink:

Oooh.... Do you mean _only_ specifying the `title` and `subtitle` **_without**_ the template type? As a form of _'simplifying'_ the answer?

**Comment by zachthompson** [comment]
If we can move away from autotemplating entirely, that would be ideal.

**Comment by moollaza** [comment]
> Oooh.... Do you mean only specifying the title and subtitle without the template type? As a form of 'simplifying' the answer?

Yup, in the Perl and then we can infer we're dealing with a Goodie, and it should use the `Text` template. So at least the language is consistent and for all the Goodies that _only_ have a title + subtitle you don't need to write out as much code.

> If we can move away from autotemplating entirely, that would be ideal.

Thanks @zachthompson! It sounds like we have our answer @GuiltyDolphin. Let's remove autotemplates (simplified structured_answer) from the Docs and get the lingering Goodies converted

**Comment by GuiltyDolphin** [comment]
@moollaza Sweet. Not heard it referred to as 'autotemplating' before though!

**Comment by talsraviv** [comment]
This is cool to catch up on. @moollaza by removing from docs would that be just convert it to using a text template, explicitly specifying it for now?
