### ISSUE TITLE
Require additional information in Maintainer requests

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#45]
Things such as "Why do you want to maintain this Instant Answer?", "What experience do you have that might help to improve this Instant Answer?" etc.

/cc @zekiel

**Comment by zekiel** [comment]
Will add a template

**Comment by zekiel** [comment]
addressed w/ commit c21c3d463377c36bedf5f3cbacd07e4cb5b7a387
