### ISSUE TITLE
Use Code Climate for linting

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#48]
@talsraviv Code Climate just got a shiny, new, [_markdown linter_](https://docs.codeclimate.com/docs/markdownlint), rules for which can be found [here](https://github.com/mivok/markdownlint/blob/v0.2.1/docs/RULES.md) (there's a bunch!).

We could use this to enforce consistency across the docs, as well as detecting various errors! It is highly configurable (by the looks of it), so we could easily adapt it to suit our own particular preferences.

/cc @moollaza

**Comment by moollaza** [comment]
That seems pretty useful, I don't have any objections to testing it out

**Comment by talsraviv** [comment]
Nice. Will take a look

**Comment by talsraviv** [comment]
That's cool to just read the rules first off :) 

@moollaza is this something we'd do in github? Do we already use codeclimate? What needs to be done?

**Comment by talsraviv** [comment]
![screen shot 2016-04-04 at 10 56 28 am](https://cloud.githubusercontent.com/assets/1065307/14252119/e9acf7d2-fa53-11e5-91af-fae39b16f9f6.png)

@moollaza okay to send this request or better to go through another way to integrate CodeClimate with our docs repo?

**Comment by GuiltyDolphin** [comment]
@talsraviv We can test it out 'locally' - i.e, on my or your branch, but I don't think there'd be any issues trying it on the main repo - it should work on a PR branch AFAIK.
