### ISSUE TITLE
Tour Translation

### ISSUE THREAD

**Issue by leso-kn** [duckduckgo/duckduckhack-docs#49]
Hey guys!

I recently wanted to "convince" (can you even say that? ;)) someone to use DDG, but i realized, that i could have been able to "convince" him a lot faster if the tour-page would have been in his language.. :J

So i was wondering if you could add the tour page to the list of translatable sites on duck.co, that'd be awesome! :D

Thanks and have a nice weekend!

**Comment by talsraviv** [comment]
Hi @leso-KN - that's great feedback - what page precisely was he stuck on? Or if multiple pages, feel free to post the URLs. That way it's easier to know what can be internationalized and what's not yet on that platform.

**Comment by leso-kn** [comment]
Thanks for the fast reply.

It was on https://duckduckgo.com/tour

(Sry for the late response; Vacation... ;))

**Comment by talsraviv** [comment]
@leso-KN no worries - I asked the team internally - translations are a known project but intentionally will be pushed back for a bit to make room for objectives that the team decided should come first. 

But yes, definitely agreed.

**Comment by leso-kn** [comment]
Understandable; No problem ;)

Thank you and have a nice weekend!
