### ISSUE TITLE
"Tennis help" example no longer works

### ISSUE THREAD

**Issue by spagy** [duckduckgo/duckduckhack-docs#52]
The [intro page](https://github.com/duckduckgo/duckduckhack-docs/blob/master/ddh-intro.md) gives the example of "tennis help" as a search query that should "show a perfect result, above any ads or regular links". Only thing is the [tennis cheat sheet](https://duck.co/ia/view/tennis_cheat_sheet) IA isn't triggered by the work "help" any more. So the example doesn't do anything.

This seems to be because the IA is a cheat sheet of the type "reference" and only "guide"s are triggered by the word "help".

This is an issue but I'm not sure whether the solution is to update the documentation or to change the IA trigger. It seems better, to me, to change the IA to make this work again. But I don't know whether the change that broke this was on purpose or not.

**Comment by spagy** [comment]
I've just had a look at the [cheat sheet reference](https://github.com/duckduckgo/duckduckhack-docs/blob/master/frontend-reference/cheat-sheet-reference.md) page. It has five examples in the cheat sheet ideas section. The link text and the search that is linked to sometimes different.

| Link Text | Activates IA | Link Destination | Activates IA |
| --- | --- | --- | --- |
| Regex help | No | regex help | No |
| Anniversary meanings | No | anniversary help | No |
| Cryptography terms and help | No | cryptography cheat sheet | Yes |
| Harry Potter spells | No | harry potter spells cheat sheet | Yes |
| Tennis info | No | tennis cheat sheet | Yes |

It looks like these IAs also need to be changed or the docs need to be updated to reflect the new implementation.

**Comment by talsraviv** [comment]
@GuiltyDolphin @moollaza @zachthompson thoughts? Is this good feedback for the cheat sheet template/trigger change, or is it something to account for in the docs?

Thanks @Spagy for bringing this up.

**Comment by GuiltyDolphin** [comment]
@Spagy Thanks for letting us know!

@talsraviv @zachthompson It looks like the 'anniversary' and 'tennis' cheat sheets aren't really 'help' cheat sheets so I think we should probably update the docs rather than add the trigger to them (I should have noticed this when I did the update a while back). I'm a bit more fency with regex... Thoughts @zachthompson ?

For the others, I think having link text differing from search term is fine, but changing the wording wouldn't hurt.

**Comment by zachthompson** [comment]
Some of these should probably still trigger:
- Anniversary meanings
- Harry Potter spells
- Tennis info (borderline)

The others we should update with different examples.

**Comment by spagy** [comment]
To me, it makes more sense for the text and search term to be the same. The context seemed to show that the text was an example search and the link a demonstration of that term.

There wouldn't be any negatives of the text and search term being the same would there?

**Comment by GuiltyDolphin** [comment]
@zachthompson I'm not sure those were triggering in the first place?

**Comment by talsraviv** [comment]
@Spagy agree with that

@GuiltyDolphin @zachthompson so far the foolproof thing has been to just change them all to cheatsheet. Not the best demonstration of the breadth of triggering but at least they work.

Is this something that suggests improvement to the cheat sheet triggering/templating mechanism?

**Comment by GuiltyDolphin** [comment]
@talsraviv There is a bunch of work in progress and discussion for improving the triggering! (See for example duckduckgo/zeroclickinfo-goodies#2781 and duckduckgo/zeroclickinfo-goodies#2777). Hopefully after resolution of those the triggering will be greatly improved (and we'll have more examples to use!).

**Comment by zachthompson** [comment]
The `ignore` feature doesn't directly help here and the categories are some time off.   We have the ability to tweak triggers enough already to fix these.

**Comment by GuiltyDolphin** [comment]
@zachthompson Indeed we do!

What do you want to do about these ones then? Seeing as the only ones that aren't triggering when they are 'supposed' to use `help` perhaps we should move `help` into a more generic category? Or perhaps add it to `reference`?

**Comment by zachthompson** [comment]
@guiltydolphin yes, something along those lines.  If you want to give it a shot and ping us in a pr we can see what it looks like.
