### ISSUE TITLE
Use Templating

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckhack-docs#53]
GitBook provides a [templating system](http://help.gitbook.com/format/templating.html) that allows us to specify re-usable variables and sections of markup to be used in multiple places.

I think this would be a good move - we have quite a lot of snippets that are repeated in multiple places throughout the docs; this would make it easier to update all of these at once, as well as reduce any typos copying up.

What's more, if we ever change which system we are using (GitBook, RTD, whatever), it should be relatively easy to move the snippets over.

Thoughts @talsraviv @moollaza?

**Comment by talsraviv** [comment]
Nice. I didn't know about this feature.

I will keep this in mind as I make edits, perhaps next time we have to update contact URLs or something. @GuiltyDolphin @moollaza any particular place you would start that I'm not thinking about?

**Comment by GuiltyDolphin** [comment]
@talsraviv A good start might be updating some of the common links to 'variables' (such as the QuackSlack email, repo links etc.) which would help reduce any typos for those.

For example:

In `book.json`:

``` json
    ...
    "variables": {
        "slackEmail": "mailto:QuackSlack@duckduckgo.com?Subject=AddMe"
    }
```

Then to use it:

``` markdown
...
Why not [contact us on Slack]({{ book.slackEmail }})
...
```

**Comment by talsraviv** [comment]
Alright! We're in business: 

https://github.com/duckduckgo/duckduckhack-docs/commit/f632fb44eced4cdc6249f7615e6b05972fb07c96

Good find!

**Comment by GuiltyDolphin** [comment]
@talsraviv Sweet!
