### ISSUE TITLE
No mention of some meta properties

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/duckduckhack-docs#74]
There is no mention of optional some meta properties like following in the docs:
- selectedItem
- scrollToSelectedItem

I'd like to add them to the docs, once someone confirms this.

@edgesince84 @moollaza @zekiel @talsraviv

**Comment by edgesince84** [comment]
I'll get confirmation on it quickly!

**Comment by moollaza** [comment]
@sahildua2305 please add them!
