### ISSUE TITLE
Fix current examples provided on "Variants Reference" Page

### ISSUE THREAD

**Issue by manrajgrover** [duckduckgo/duckduckhack-docs#88]
Currently, many IA examples mentioned on the [page](http://docs.duckduckhack.com/frontend-reference/variants-reference.html) don't work. One example is "[electronics coupons](https://duckduckgo.com/?q=electronics+coupons&ia=web)" mentioned under `detail` variants.

**Comment by himanshu1603** [comment]
@ManrajGrover I would like to work on this issue.

**Comment by manrajgrover** [comment]
@himanshu1603 Although DuckDuckHack is currently in maintenance mode, I feel this one can be fixed.

@moollaza Please let me know if can give a go-ahead here.
