### ISSUE TITLE
Document that places template group requires maps

### ISSUE THREAD

**Issue by sekhavati** [duckduckgo/duckduckhack-docs#89]
The documentation omits to mention that in order for mapping functionality to work with the `places` template group the call to `Spice.add()` must be wrapped within a require block that imports `maps`, ie:

`DDG.require(['maps'], function() { Spice.add( ...`

http://docs.duckduckhack.com/frontend-reference/template-groups.html#places-template-group

**Comment by Divya063** [comment]
@sekhavati Can I work on this?
